SELECT md.TRADEDATE, 
md.SECID,
md.SHORTNAME,
md.OPEN,
md.HIGH,
md.LOW,
md.CLOSE,
md.MARKETPRICE2,
md.WAPRICE,
md.VOLUME

FROM MOEXDATA md 

where md.SECID in (SELECT SECID from MOSCOW_EXC_INDEX) and md.SECID = 'GAZP' and DATE(md.TRADEDATE) = '2024-05-27'


